wandb_version: 1

model_name:
  desc: null
  value: Simple_net
optimizer:
  desc: null
  value: Adam
criterion:
  desc: null
  value: PWRSWtL
learning_rate:
  desc: null
  value: 0.001
epochs:
  desc: null
  value: 2
_wandb:
  desc: null
  value:
    python_version: 3.11.4
    cli_version: 0.16.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1710838416.677323
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.11.4
      5: 0.16.0
      8:
      - 3
      - 5
      13: windows-amd64
